name: Setup project and run e2e tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '40 10 * * *'

jobs:
  run-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3

      - name: Setup docker compose environment
        uses: docker/setup-compose-action@v1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: v18.19.1
          cache: 'npm'
          cache-dependency-path: ./test/package-lock.json

      - name: Start the server
        run: docker compose up -d

      - name: Wait for openlibrary server
        run: |
          sudo apt-get install wait-for-it -y
          wait-for-it -h localhost -p 8080 -t 10

      - name: Run e2e tests
        working-directory: ./test
        id: test
        run: |
          npm install
          npx playwright install chromium
          npx playwright test e2e

      - name: Log tracing results
        working-directory: ./test
        if: ${{ failure() && steps.test.conclusion == 'failure' }}
        run: |
          echo "To view a trace, run the following command(s) locally:"
          for f in test-results/*/*.zip; do
              echo "npx playwright show-trace $f"
          done
